### ISSUE TITLE
Component Proposal: Arduino Micro

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#102]
As the first assembly (#92) goes, we found that the Arduino Nano has problems connecting to the Raspberry Pi. Therefore, we are considering purchasing another Arduino Micro which has been validated. An Amazon link is attached below, but we may also go with other options. Just note that we want it **with headers**.

https://www.amazon.ca/Arduino-Micro-with-Headers-A000053/dp/B00AFY2S56

**Comment by qmascarenhas** [comment]
It's on its way ... you should have it for Monday.

**Comment by ATATC** [comment]
Is there any USB-A to Micro USB cable at school? Cuz we'll need one.

**Comment by qmascarenhas** [comment]
There is a short one in rm217 that should suffice for now until we complete the module layout for installation on VeC99.

**Comment by ATATC** [comment]
Item received.
