### ISSUE TITLE
Redesign the Home Page

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#103]
During the past versions, leads.projectneura.org has always been the documentation page. Now we are considering building a single-slide project homepage. This is an open task that anyone can contribute to. The website will be a separate repository (not created yet).

This task involves:
- Website design
- Frontend tech stack
- HTML
- CSS
- Javascript
- Version Control through GitHub

**Comment by ATATC** [comment]
@qmascarenhas Maybe choose someone to do this as it is one of the easier ones?

**Comment by qmascarenhas** [comment]
@fz20181223luogu Would you be interested in taking this on?

**Comment by ATATC** [comment]
An example:
![1e8c4a49e9736d7d62b2dbf12c68b08](https://github.com/ProjectNeura/LEADS/assets/52603299/a5087dd4-bedc-48c8-9af6-899e067815cb)

**Comment by fz20181223luogu** [comment]
> @fz20181223luogu Would you be interested in taking this on?

I'm afraid that I could not, since I have very little knowledge about programming languages related to websites.

**Comment by ATATC** [comment]
These languages are very easy to learn. If you could do this it would save us lots of time.

**Comment by ATATC** [comment]
@fz20181223luogu Any update?
