### ISSUE TITLE
USB GPS Receiver Lookup & Purchase

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#14]
ASSIGNED to @fz20181223luogu

Please post any updates here.

**Comment by qmascarenhas** [comment]
@ATATC Not sure if you saw the 2 modules that @fz20181223luogu sourced:
1. [BN-880 GPS Module](https://www.amazon.ca/dp/B086ZKFFY4)
2. [BDS QZSS HAT Expansion Board GPS Module L76X for Raspberry Pi Fast Positioning, High Accuracy, Low Power Consumption](https://www.amazon.ca/Expansion-Raspberry-Positioning-Accuracy-Consumption/dp/B0918Z118S)

**Comment by ATATC** [comment]
Actually I prefer U-Blox modules. These just work but are not perfect.

**Comment by ATATC** [comment]
As these two also require wiring like U-Blox products, I don't think they are very advantageous.

**Comment by qmascarenhas** [comment]
How about this [MAX-10S, SMA (Qwiic)](https://www.sparkfun.com/products/18037) instead of the [NEO-M9N, SMA (Qwiic)](https://www.sparkfun.com/products/17285)?
The other option is going for the [NEO-M9N, U.FL (Qwiic)](https://www.sparkfun.com/products/15712) with a [SMA to U.FL interface cable](https://www.sparkfun.com/products/9145).

**Comment by qmascarenhas** [comment]
@ATATC #39 [VK-162 G-Mouse USB GPS Dongle](https://www.amazon.ca/Navigation-External-Receiver-Raspberry-Geekstory/dp/B078Y52FGQ/ref=sr_1_2_sspa?crid=2XXTFD7YO36G7&dib=eyJ2IjoiMSJ9.tilH0HvRvDYEwApcuenax2lgwBGzW3xm5bKo6Glet0fFP0U7Z8_Xi1cr3hHUCAfRzfuowJaPU3aUfw0D3vS8R7eU1H4eQipQ3tcDVWBJvpmaoKJr2PPV4EyaXYIHOxoQYdTNyKNfW4yqRllnyaoGKGcSyN1Tk3e32Edr71r4kbBAIkv9NHfoEbKUjh5zVpuMYfh5IV6rSploNK65qMNgfkayQE6CWLYYEAzR2wNMt6CcWRguIEsCO7vs2Zy0UFIQxVOWpFvFkFgdRMb_U4WkTu0jXcSdEEFecBVWobCZEqo.XBI5MlaVeTOvgrD-qypPfTT-tf0rLo73JaUK44jEXBE&dib_tag=se&keywords=usb%2Bgps%2Breceiver&qid=1711206728&sprefix=USB%2BGPS%2Caps%2C75&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1) for $24.99 from Amazon works for me. Please confirm that you would like me to order this.

**Comment by ATATC** [comment]
Yes.

**Comment by qmascarenhas** [comment]
Done.
