### ISSUE TITLE
Camera Lookup & Purchase

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#15]
ASSIGNED to @RiHenry

Please post any updates here.

**Comment by RiHenry** [comment]
I have discovered a camera from the company arducam that I addressed in the meetings before the break that could be suitable for our uses. 
https://www.arducam.com/product/b0205-arducam-1080p-day-night-vision-usb-camera-module-for-computer-2mp-automatic-ir-cut-switching-all-day-image-usb2-0-webcam-board-with-ir-leds/ 
it is their 1080p camera and it costs 34.99 on uc tronics. It is a 2mp 1920 x 1080 camera 
It is a usb camera that does have infared if needed.

**Comment by RiHenry** [comment]
A similar but a slightly higher quality and price arducam would be the 8mp 1080p camera
It is 42.90 but higher quality. 
https://ca.robotshop.com/products/arducam-8mp-1080p-usb-camera-module

**Comment by ATATC** [comment]
I think either looks fine.

**Comment by ATATC** [comment]
> I have discovered a camera from the company arducam that I addressed in the meetings before the break that could be suitable for our uses. https://www.arducam.com/product/b0205-arducam-1080p-day-night-vision-usb-camera-module-for-computer-2mp-automatic-ir-cut-switching-all-day-image-usb2-0-webcam-board-with-ir-leds/ it is their 1080p camera and it costs 34.99 on uc tronics. It is a 2mp 1920 x 1080 camera It is a usb camera that does have infared if needed.

This seems better.

**Comment by RiHenry** [comment]
what must be noted is that the 2mp 1080p infared camera can not be found shipping to canada so we will have to compromise with the 8mp camera without infared

**Comment by ATATC** [comment]
> what must be noted is that the 2mp 1080p infared camera can not be found shipping to canada so we will have to compromise with the 8mp camera without infared

@qmascarenhas

**Comment by ATATC** [comment]
> A similar but a slightly higher quality and price arducam would be the 8mp 1080p camera
> 
> It is 42.90 but higher quality. 
> 
> https://ca.robotshop.com/products/arducam-8mp-1080p-usb-camera-module

There's only one unit left.
@RiHenry @qmascarenhas

**Comment by RiHenry** [comment]
Could we purchase it?

**Comment by ATATC** [comment]
Unfortunately we need at least 4 I believe.

**Comment by RiHenry** [comment]
Sorry this is a late comment but we could choose the other option
