### ISSUE TITLE
Add Postprocess Analysis

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#173]
As it is discussed in the meeting, we want some post-process analysis as it leaves us more time to run more complex algorithms.

**Comment by ATATC** [comment]
There are still some errors in identifying laps.

**Comment by ATATC** [comment]
## Demo
@qmascarenhas Check this out.

A lap from last year's data:

![image](https://github.com/ProjectNeura/LEADS/assets/52603299/753f4d13-7733-4253-8710-050a5d295f81)

Comparison between all laps last year:

![image](https://github.com/ProjectNeura/LEADS/assets/52603299/68c149b0-1392-4bbd-92d3-f620c51da9e3)

**Comment by ATATC** [comment]
- [ ] Add a label for the color bar

**Comment by ATATC** [comment]
![lap10](https://github.com/ProjectNeura/LEADS/assets/52603299/82e9afd8-e10b-47e2-ab7d-8e4cc12e12e2)

**Comment by qmascarenhas** [comment]
@ATATC That's awesome!!

**Comment by ATATC** [comment]
- [ ] Add suggestion generators

**Comment by ATATC** [comment]
- [ ] Add a page on the docs website to generate scripts

**Comment by ATATC** [comment]
- [ ] Make `matplotlib` optiona
- [ ] Export the static methods to a separate file
- [ ] Export the inferences to a separate file
