### ISSUE TITLE
Error Voltage Readings

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#182]
We found in #92 that the voltage sensor readings were off.

**Comment by ATATC** [comment]
Temporarily fixed.

**Comment by qmascarenhas** [comment]
@ATATC can you point me to the code for this?

**Comment by ATATC** [comment]
If you find on the page,
<img width="854" alt="image" src="https://github.com/ProjectNeura/LEADS/assets/52603299/5d1b69cb-6200-4e3b-b280-3f186ccc0701">
Click there and you will be redirected to the change.

**Comment by ATATC** [comment]
And the Arduino code: https://github.com/ProjectNeura/LEADS-Arduino/commit/c2d573d26187338d900b5aaef2aa08859ae94189

**Comment by ATATC** [comment]
@qmascarenhas Pointed out a more reasonable solution (https://github.com/ProjectNeura/LEADS-Arduino/commit/c2d573d26187338d900b5aaef2aa08859ae94189#commitcomment-142288646).

**Comment by ATATC** [comment]
I've updated the algorithm according to the resistance stated here: https://www.osepp.com/downloads/pdf/VoltageSensor.pdf.
