### ISSUE TITLE
Test: OpenCV Performance on Raspberry Pi

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#254]
Huge progress has been made in regard to video support in the past few pull requests. However, concerns about the performance of the Raspberry Pi do exist as the testing platform, Apply M3 Pro, is only able to provide a video feed at almost 30fps. Therefore, it is likely that OpenCV runs as slowly as GStreamer does on the Raspberry Pi. This poor performance wouldn't affect the dashboard anyway though.

Ideally, this is what we have accomplished so far:
<img width="832" alt="image" src="https://github.com/ProjectNeura/LEADS/assets/52603299/f3b469e9-a0df-4c6b-83ac-1046af6eae83">
<img width="1512" alt="image" src="https://github.com/ProjectNeura/LEADS/assets/52603299/23d7aff3-23e5-492f-bbf1-77d43325bcdf">

The monitor is just an additional widget. You can still switch back to other widgets.
It now supports up to 4 cameras, of which 1 is enabled in this case, which are front view, left view, right view, and rear view respectively.

**Comment by ATATC** [comment]
The performance of the raspberry barely supports OpenCV. The bottleneck seems to be encoding and decoding.

**Comment by ATATC** [comment]
Trying on a virtual machine to see the minimum requirement.

**Comment by ATATC** [comment]
The bottleneck is Pillow.

**Comment by ATATC** [comment]
If use OpenCV instead, it consumes 10%.

**Comment by ATATC** [comment]
@qmascarenhas Is it possible to schedule this test for Monday during the second period or after school?

**Comment by qmascarenhas** [comment]
yes - we could do that.

**Comment by ATATC** [comment]
@qmascarenhas That period just got occupied. What about Tuesday's last period?

**Comment by ATATC** [comment]
Raspberry Pi fails to run `devices_visual.py`.
