### ISSUE TITLE
Throttle Pedal Lookup & Purchase

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#27]
Lookup and purchase a throttle pedal.

**Comment by qmascarenhas** [comment]
In stock we have:

1. [Kelly 0-5k Throttle Pedal](https://kellycontroller.com/shop/kelly-0-5k-throttle-pedal/)
2. [Thumb Throttle(right side)](https://kellycontroller.com/shop/thumb-throttle/)

**Comment by ATATC** [comment]
What format does the 0-5k Throttle Pedal output?
