### ISSUE TITLE
GSM Module Feasibility Verification

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#43]
Verify the feasibility of adding a GSM module to the Raspberry Pi.

**Comment by ATATC** [comment]
@qmascarenhas how does this look?
https://www.jeffgeerling.com/blog/2022/using-4g-lte-wireless-modems-on-raspberry-pi

**Comment by qmascarenhas** [comment]
@ATATC This doc is precisely what we’re looking for b/c there’s lots of little nuances that we’ll run in to and it would help to have a single resource to reference instead of scouring the web. I’d probably go for the hat option unless we have enough real estate.

**Comment by ATATC** [comment]
https://github.com/Civlo85/gsmHat seems to serve the purpose.

**Comment by ATATC** [comment]
https://www.waveshare.com/SIM7600A-H-4G-HAT.htm
It's designed for North American scenarios and it states that it "comes with development resources and manual (examples for Raspberry Pi/Jetson Nano/Arduino/STM32)"

**Comment by ATATC** [comment]
Most tutorials I found used modules from Waveshare although it's a Chinese company based in Shenzhen. I did not find any known issues regarding the hats in the limited number of references on Google. There is a detailed doc written by the manufacturer: https://www.waveshare.com/wiki/SIM7600A-H_4G_HAT.

**Comment by ATATC** [comment]
There is a problem though, I am not sure whether it works as a system-level adapter like WiFi.

**Comment by ATATC** [comment]
Under current circumstances I don't think it's worth taking extra time to dig into. We can leave it in VeC 3.0.
