### ISSUE TITLE
Test: the Wheel Speed Sensor System

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#47]
We should schedule a test for the wheel speed sensor system.
@qmascarenhas

**Comment by qmascarenhas** [comment]
How about your weekly meeting day on Wednesday?

**Comment by ATATC** [comment]
Should be good.

**Comment by ATATC** [comment]
# Toady
It did work.
Did not have a chance to check the accuracy.

**Comment by qmascarenhas** [comment]
Got VeC99 running this morning P2. @ATATC if you brought your kit, we can test over lunch P3c. Let me know.

**Comment by ATATC** [comment]
Sure. I brought it.

**Comment by ATATC** [comment]
I'm gonna see you after lunch.

**Comment by ATATC** [comment]
VERSION `0.5.1` COMMIT 4660b6e0
Great success.
