### ISSUE TITLE
Wheel Speed Sensor Shell Design

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#58]
Please design or assign someone to design a shell for the wheel speed sensor to prevent sand and gravel from damaging the sensor. Please upload your work to the design folder.

**Comment by qmascarenhas** [comment]
@ATATC please assign this task to @RiHenry - I will discuss details with him next week. @RiHenry please schedule a meeting with me on Tuesday after school if possible please.

**Comment by RiHenry** [comment]
![image](https://github.com/ProjectNeura/LEADS/assets/152418899/ce8f9c6c-7014-4bb8-b17a-d012e81f1860)

**Comment by ATATC** [comment]
@qmascarenhas @RiHenry If the model is fixed please check in to upload the file.
