### ISSUE TITLE
Display Lookup & Purchase

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#6]
Lookup and purchase a display.

**Comment by qmascarenhas** [comment]
@ATATC can you please send @SAKajiura the display specs?

**Comment by ATATC** [comment]
I've contacted the manufacturer for the CAD file.

**Comment by qmascarenhas** [comment]
@ATATC can you post a link to the item in the meantime? I think @SAKajiura just needs the overall dimensions to get started although the CAD file would be useful eventually to finalize the fit.

**Comment by ATATC** [comment]
I mean yeah sure but it's all Chinese.

**Comment by ATATC** [comment]
【淘宝】https://m.tb.cn/h.5sfZe6S12Y21MaM?tk=RmuHWjz1D0f CZ3460 「树莓派显示屏4B3B便携式4.3寸5寸7寸10.1寸hdmi免驱动VGA机箱副屏」
点击链接直接打开 或者 淘宝搜索直接打开

**Comment by ATATC** [comment]
Resolution: 800x480
Scale: 120.7x75.8

**Comment by qmascarenhas** [comment]
Who's the manufacturer? That link does not work for me.

**Comment by ATATC** [comment]
A Chinses company whose name I've never heard of.

**Comment by SAKajiura** [comment]
I wanted to know the dimensions in inches or centimeters. The website doesn't say.

**Comment by ATATC** [comment]
> Resolution: 800x480 Scale: 120.7x75.8

@SAKajiura These are in millimeters.

**Comment by SAKajiura** [comment]
Oh. Sorry. It wasn't clear.

**Comment by SAKajiura** [comment]
What about the thickness?

**Comment by ATATC** [comment]
I'm gonna ask the manufacturer or we can measure it ourselves.

**Comment by ATATC** [comment]
They said they do have the CAD file but they are on vacation now. It'll have to be after the Chinese New Year for us to get that.
