### ISSUE TITLE
Add Historical Traces to the Map

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#72]
To better analyze and improve driving strategies, we want the historical traces to be displayed as a floating layer on the map. A detailed introduction will be later added in a periodic report.

**Comment by ATATC** [comment]
See https://github.com/ProjectNeura/LEADS/blob/master/docs/reports/2024-03-07.md.

**Comment by ATATC** [comment]
> Here's the [.gpx data for the 2023 Waterloo EV Challenge](https://villanovaonline.sharepoint.com/:u:/s/VeC2.0DesignTeam-Rear-WheelDriveandPowertrain/EeNWat19njtGjyaQwnwgWyoBvr6-ctJUhpgl4CAGoNgTeQ?e=JUXRJo) downloaded from Strava. You will need to scrub the data to get the course route with and without the pit. There's some extraneous data as well but I am sure you will be able to pick that out. Here's the [Strava link](https://www.strava.com/activities/9151206463?utm_content=101944146&utm_medium=referral&utm_source=twitter%20#strava) if you want to view the data on their app but it's easy enough to upload to google earth/maps.

**Comment by ATATC** [comment]
[Waterloo_Electric_Vehicle_Challenge_2023.txt](https://github.com/ProjectNeura/LEADS/files/14527089/Waterloo_Electric_Vehicle_Challenge_2023.txt)

**Comment by qmascarenhas** [comment]
> See https://github.com/ProjectNeura/LEADS/blob/master/docs/reports/2024-03-07.md.

@HaydenHour Please see one of us if you have any questions about this task.

**Comment by ATATC** [comment]
Accidentally mentioned this issue. It should be #73.

**Comment by qmascarenhas** [comment]
@HaydenHour Any update on this? Can you give us some more information on where you're stuck?

**Comment by HaydenHour** [comment]
@ATATC @qmascarenhas Sorry I did not post sooner, I did not have access to my laptop over the weekend. It appears that the code is hitting an issue when trying to read the GPX file (specifically regarding the parse function on line 10). This is my code below:

import gpxpy

def gpx_to_custom_csv(gpx_file_path, output_csv_file_path):

    # Open GPX file
    with open(gpx_file_path, 'r') as gpx_file:

        #Issue appears to be here with the parse
        gpx = gpxpy.parse(gpx_file)

        # write data in CSV format
    with open(output_csv_file_path, 'w') as csv_file:
        for track in gpx.tracks:
            for segment in track.segments:
                for point in segment.points:
                    # Write latitude and longitude separated by semicolon
                    csv_file.write(f"{point.latitude};{point.longitude},")

# file paths:
gpx_file_path = "C:/Users/hayde/OneDrive/VeC/Waterloo_Electric_Vehicle_Challenge_2023.gpx"
output_csv_file_path = "C:/Users/hayde/OneDrive/VeC/VEC2023_CSV.csv"
gpx_to_custom_csv(gpx_file_path, output_csv_file_path)

**Comment by ATATC** [comment]
Please provide the error message.

**Comment by ATATC** [comment]
This works for me.

**Comment by HaydenHour** [comment]
Oh, that's weird. So did it create a new file with the right formatting?

**Comment by ATATC** [comment]
I haven't tested the file part. I replaced it with `print()`. But I believe `write` overwrites the file. There should be an appending function.

**Comment by ATATC** [comment]
Btw please fork the repository to be ready to merge your contributions.

**Comment by ATATC** [comment]
I'm gonna finish this feature (including auto corner speed marking) for the website this week.

**Comment by qmascarenhas** [comment]
This is excellent @ATATC !

**Comment by ATATC** [comment]
@HaydenHour Sorry for the wrong instructions previously. I had some misunderstanding about CSV files. I'll provide a new handout later.

**Comment by ATATC** [comment]
[2023.csv](https://github.com/ProjectNeura/LEADS/files/15315473/2023.csv)

**Comment by ATATC** [comment]
## Result

An enhanced version with inferred speeds.

[2023.csv](https://github.com/ProjectNeura/LEADS/files/15315768/2023.csv)

```python
from gpxpy import parse
from leads.data_persistence import CSVCollection
from leads.data import dlat2meters, dlon2meters


def gpx_to_custom_csv(gpx_file_path: str, output_csv_file_path: str) -> None:
    with open(gpx_file_path, 'r') as gpx_file:
        gpx = parse(gpx_file)
    csv = CSVCollection(output_csv_file_path, ("t", "voltage", "speed", "front_wheel_speed", "rear_wheel_speed",
                                               "forward_acceleration", "lateral_acceleration", "mileage", "gps_valid",
                                               "gps_ground_speed", "latitude", "longitude"))
    # prev time
    t_0 = None
    # prev latitude
    lat_0 = None
    # prev longitude
    lon_0 = None
    for track in gpx.tracks:
        for segment in track.segments:
            for point in segment.points:
                t = point.time.timestamp()
                lat = point.latitude
                lon = point.longitude
                if t_0 is None or lat_0 is None or lon_0 is None:
                    t_0, lat_0, lon_0 = t, lat, lon
                    csv.write_frame(int(t * 1000), *((None,) * 9), lat, lon)
                    continue
                # dt
                dt = t - t_0
                dlat = lat - lat_0
                dlon = lon - lon_0
                # dy
                dy = dlat2meters(dlat)
                # dx
                dx = dlon2meters(dlon)
                # c
                hyp = (dy ** 2 + dx ** 2) ** 0.5
                print(hyp, dt)
                # v
                v = hyp / dt
                # m/s to km/h
                v *= 3.6

                t_0 = t
                lat_0 = lat
                lon_0 = lon

                csv.write_frame(int(t * 1000), None, v, v, v, *((None,) * 5), lat, lon)


gpx_to_custom_csv("Waterloo_Electric_Vehicle_Challenge_2023.gpx", "data/2023.csv")
```
