### ISSUE TITLE
Add an Analog Speedometer for Better Readability

### ISSUE THREAD

**Issue by SAKajiura** [ProjectNeura/LEADS#83]
I think that we should use analog speedometer because it is easier to read.

Maybe we could create something that looks similar to the image below.

![image](https://github.com/ProjectNeura/LEADS/assets/152184477/5af27605-98c6-454a-be7b-5bf341bafdf0)

It should have a needle that extends fully.

![image](https://github.com/ProjectNeura/LEADS/assets/152184477/1b99766f-45e9-4128-ae57-aac84357de62)

**Comment by ATATC** [comment]
Are you suggesting a new hardware speedometer or an enhancement to the software?

**Comment by ATATC** [comment]
Default font sizes have been increased. An update for the preview screenshot will be scheduled.

**Comment by ATATC** [comment]
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/5a9946f8-a928-49df-9e69-639664acd5fd)

**Comment by ATATC** [comment]
You can still change it to the classic style by clicking it.

**Comment by ATATC** [comment]
NEXT
- [ ] Rename "mode" to "style"
- [ ] Support specifying style
- [ ] Support disabling default click call back that switches the style

**Comment by SAKajiura** [comment]
Looks good.

**Comment by ATATC** [comment]
NEXT

- [ ] Implement the third style.

**Comment by ATATC** [comment]
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/ed04c6d1-f98b-4e1c-8957-fa69d0a248c5)
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/ded08471-3cb5-4091-8212-4bb597dc7f1b)
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/290ec3cf-7ab0-4e76-bf6a-10a9f819338b)

**Comment by ATATC** [comment]
# Improved UI
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/fd67c1a0-c607-41ff-a4a7-746ec17c3334)
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/69e52787-9abb-4caa-a116-91dc23adffff)

The color of the arc changes according to the speed.
