### ISSUE TITLE
Implement a Hardware Low Pass Filter

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#86]
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/7166ed01-64d1-4f3a-95b0-c2925f2c875c)

# Function
## Input
A PWM analog input
## Output
The average voltage of the PWM input

**Comment by qmascarenhas** [comment]
@ATATC can you point me to the codeset instruction where you are generating the input to the LPF? Are you sure it is a [PWM](https://www.electronics-tutorials.ws/blog/pulse-width-modulation.html) signal? The signal you are showing on the diagram is not a PWM signal.
Anyway, assuming it is a PWM signal, a [single pole RC (passive) LPF should suffice](https://www.allaboutcircuits.com/technical-articles/low-pass-filter-a-pwm-signal-into-an-analog-voltage/).

**Comment by ATATC** [comment]
That blog seems to be what we want. I did not really look into the diagram.

This is how we control the motor:
https://gpiozero.readthedocs.io/en/stable/api_output.html#motor
