### ISSUE TITLE
Implement the G Force Recording System

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#87]
- Complete `GForceMeter`
- Include G force data in the default data container yet
- Create data persistence for G force data in `leads_vec_rc` 
- Include G force data in the remote analyst

**Comment by qmascarenhas** [comment]
Does the rpi4 have a built-in accelerometer?

**Comment by ATATC** [comment]
Unfortunately no.

**Comment by ATATC** [comment]
We need an external at least 6 DoF accelerometer.

**Comment by qmascarenhas** [comment]
here's where the Phyphox feature would come in handy.

**Comment by ATATC** [comment]
Bug found: render delay significantly increases after 30 seconds.

**Comment by ATATC** [comment]
Resources are wasted on unnecessary re-rendering.

**Comment by ATATC** [comment]
Replacing the dynamically drawn circles with a fixed image is worth trying.

**Comment by ATATC** [comment]
> CPU usage still increases extremely as long as the G force meter is rendered.

It is confirmed that this is caused only by the G force meter.

**Comment by ATATC** [comment]
Investigating.

**Comment by ATATC** [comment]
Bug fixed.

**Comment by ATATC** [comment]
https://learn.adafruit.com/adafruit-9-dof-orientation-imu-fusion-breakout-bno085/uart-rvc-for-arduino
