### ISSUE TITLE
Component Proposal: 9-DOF IMU (Accelerometer)

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#91]
As it is described in #87, we need a hardware accelerometer.
The following module manufactured by Bosch is definitely outstanding as it provides a built-in fusion algorithm. Usually, these algorithms consume huge amounts of time to develop.
> Rather than spending weeks or months fiddling with algorithms of varying accuracy and complexity, you can have meaningful sensor data in minutes thanks to the BNO055
![image](https://github.com/ProjectNeura/LEADS/assets/52603299/da629d65-b298-46f0-9bb8-b00b218b00d7)
https://www.adafruit.com/product/4646?gad_source=1&gclid=CjwKCAjwwr6wBhBcEiwAfMEQs25ZsRQSI3ZZr5F1jnn5Rk_EU1TZqa_kDwB_7Oy19h_hhXwNvQKq0xoCyzcQAvD_BwE

**Comment by ATATC** [comment]
## Correction
I found BNO085 is a better and cheaper option, just that it's out of stock on Adafruit. You'll have to buy it on DigiKey.
https://www.adafruit.com/product/4754

**Comment by ATATC** [comment]
@qmascarenhas Please still review this proposal as the acceleration data is going to play a role in this year's development.

**Comment by ATATC** [comment]
@qmascarenhas Please still review this proposal as the acceleration data is going to play a role in this year's development

**Comment by qmascarenhas** [comment]
@ATATC ordered.

**Comment by ATATC** [comment]
Soldering required.

**Comment by ATATC** [comment]
The other side also needs soldering. P0 needs to be pulled as high to specify UART mode.
