### ISSUE TITLE
Power Consumption Table

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#94]
Provide a power consumption table to better inspect the capability requirements of the ports and cables.

**Comment by ATATC** [comment]
https://1drv.ms/x/s!AlbApt6q_F88g_ImcoMv1upCLwAzwA

**Comment by ATATC** [comment]
@qmascarenhas The table is finished.
I didn't convert the voltages, just estimated values.

**Comment by qmascarenhas** [comment]
I've ordered 2 4-port USB-A 3.0 hubs - 1 powered via usb-c ... you have a short usb-c to usb-c cable by any chance?
Hubs should be in tomorrow so you will have them for Thursday.

**Comment by ATATC** [comment]
I only have regular c to a cables. All c to c cables I have are thunderbolt.
